// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pb/gx_interface.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PccRulesProvision struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Imsi            string                 `protobuf:"bytes,1,opt,name=imsi,proto3" json:"imsi,omitempty"`
	IpAddress       string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	ActiveRuleNames []string               `protobuf:"bytes,3,rep,name=active_rule_names,json=activeRuleNames,proto3" json:"active_rule_names,omitempty"` // Список правил: ["YouTube_Premium", "Social_Unlim"]
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PccRulesProvision) Reset() {
	*x = PccRulesProvision{}
	mi := &file_pb_gx_interface_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PccRulesProvision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PccRulesProvision) ProtoMessage() {}

func (x *PccRulesProvision) ProtoReflect() protoreflect.Message {
	mi := &file_pb_gx_interface_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PccRulesProvision.ProtoReflect.Descriptor instead.
func (*PccRulesProvision) Descriptor() ([]byte, []int) {
	return file_pb_gx_interface_proto_rawDescGZIP(), []int{0}
}

func (x *PccRulesProvision) GetImsi() string {
	if x != nil {
		return x.Imsi
	}
	return ""
}

func (x *PccRulesProvision) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *PccRulesProvision) GetActiveRuleNames() []string {
	if x != nil {
		return x.ActiveRuleNames
	}
	return nil
}

type PccRulesAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsEnforced    bool                   `protobuf:"varint,1,opt,name=is_enforced,json=isEnforced,proto3" json:"is_enforced,omitempty"`
	ResultCode    uint32                 `protobuf:"varint,2,opt,name=result_code,json=resultCode,proto3" json:"result_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PccRulesAck) Reset() {
	*x = PccRulesAck{}
	mi := &file_pb_gx_interface_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PccRulesAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PccRulesAck) ProtoMessage() {}

func (x *PccRulesAck) ProtoReflect() protoreflect.Message {
	mi := &file_pb_gx_interface_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PccRulesAck.ProtoReflect.Descriptor instead.
func (*PccRulesAck) Descriptor() ([]byte, []int) {
	return file_pb_gx_interface_proto_rawDescGZIP(), []int{1}
}

func (x *PccRulesAck) GetIsEnforced() bool {
	if x != nil {
		return x.IsEnforced
	}
	return false
}

func (x *PccRulesAck) GetResultCode() uint32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

var File_pb_gx_interface_proto protoreflect.FileDescriptor

const file_pb_gx_interface_proto_rawDesc = "" +
	"\n" +
	"\x15pb/gx_interface.proto\x12\x02pb\"r\n" +
	"\x11PccRulesProvision\x12\x12\n" +
	"\x04imsi\x18\x01 \x01(\tR\x04imsi\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12*\n" +
	"\x11active_rule_names\x18\x03 \x03(\tR\x0factiveRuleNames\"O\n" +
	"\vPccRulesAck\x12\x1f\n" +
	"\vis_enforced\x18\x01 \x01(\bR\n" +
	"isEnforced\x12\x1f\n" +
	"\vresult_code\x18\x02 \x01(\rR\n" +
	"resultCode2I\n" +
	"\n" +
	"DiameterGx\x12;\n" +
	"\x11ProvisionPccRules\x12\x15.pb.PccRulesProvision\x1a\x0f.pb.PccRulesAckB\x1aZ\x18pcef-shaper-system/pb;pbb\x06proto3"

var (
	file_pb_gx_interface_proto_rawDescOnce sync.Once
	file_pb_gx_interface_proto_rawDescData []byte
)

func file_pb_gx_interface_proto_rawDescGZIP() []byte {
	file_pb_gx_interface_proto_rawDescOnce.Do(func() {
		file_pb_gx_interface_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_gx_interface_proto_rawDesc), len(file_pb_gx_interface_proto_rawDesc)))
	})
	return file_pb_gx_interface_proto_rawDescData
}

var file_pb_gx_interface_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_gx_interface_proto_goTypes = []any{
	(*PccRulesProvision)(nil), // 0: pb.PccRulesProvision
	(*PccRulesAck)(nil),       // 1: pb.PccRulesAck
}
var file_pb_gx_interface_proto_depIdxs = []int32{
	0, // 0: pb.DiameterGx.ProvisionPccRules:input_type -> pb.PccRulesProvision
	1, // 1: pb.DiameterGx.ProvisionPccRules:output_type -> pb.PccRulesAck
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_gx_interface_proto_init() }
func file_pb_gx_interface_proto_init() {
	if File_pb_gx_interface_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_gx_interface_proto_rawDesc), len(file_pb_gx_interface_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_gx_interface_proto_goTypes,
		DependencyIndexes: file_pb_gx_interface_proto_depIdxs,
		MessageInfos:      file_pb_gx_interface_proto_msgTypes,
	}.Build()
	File_pb_gx_interface_proto = out.File
	file_pb_gx_interface_proto_goTypes = nil
	file_pb_gx_interface_proto_depIdxs = nil
}
