// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: pb/gy_interface.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DiameterGy_RequestCreditControl_FullMethodName = "/pb.DiameterGy/RequestCreditControl"
)

// DiameterGyClient is the client API for DiameterGy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PCEF ➔ OCS
// Контракт онлайн-биллинга Gy: PCEF ➔ OCS Aerospike
type DiameterGyClient interface {
	// Credit-Control-Request / Answer: Резервирование и списание квантов по 10 МБ
	RequestCreditControl(ctx context.Context, in *CreditControlRequest, opts ...grpc.CallOption) (*CreditControlAnswer, error)
}

type diameterGyClient struct {
	cc grpc.ClientConnInterface
}

func NewDiameterGyClient(cc grpc.ClientConnInterface) DiameterGyClient {
	return &diameterGyClient{cc}
}

func (c *diameterGyClient) RequestCreditControl(ctx context.Context, in *CreditControlRequest, opts ...grpc.CallOption) (*CreditControlAnswer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreditControlAnswer)
	err := c.cc.Invoke(ctx, DiameterGy_RequestCreditControl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiameterGyServer is the server API for DiameterGy service.
// All implementations must embed UnimplementedDiameterGyServer
// for forward compatibility.
//
// PCEF ➔ OCS
// Контракт онлайн-биллинга Gy: PCEF ➔ OCS Aerospike
type DiameterGyServer interface {
	// Credit-Control-Request / Answer: Резервирование и списание квантов по 10 МБ
	RequestCreditControl(context.Context, *CreditControlRequest) (*CreditControlAnswer, error)
	mustEmbedUnimplementedDiameterGyServer()
}

// UnimplementedDiameterGyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiameterGyServer struct{}

func (UnimplementedDiameterGyServer) RequestCreditControl(context.Context, *CreditControlRequest) (*CreditControlAnswer, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestCreditControl not implemented")
}
func (UnimplementedDiameterGyServer) mustEmbedUnimplementedDiameterGyServer() {}
func (UnimplementedDiameterGyServer) testEmbeddedByValue()                    {}

// UnsafeDiameterGyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiameterGyServer will
// result in compilation errors.
type UnsafeDiameterGyServer interface {
	mustEmbedUnimplementedDiameterGyServer()
}

func RegisterDiameterGyServer(s grpc.ServiceRegistrar, srv DiameterGyServer) {
	// If the following call panics, it indicates UnimplementedDiameterGyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiameterGy_ServiceDesc, srv)
}

func _DiameterGy_RequestCreditControl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreditControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiameterGyServer).RequestCreditControl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiameterGy_RequestCreditControl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiameterGyServer).RequestCreditControl(ctx, req.(*CreditControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiameterGy_ServiceDesc is the grpc.ServiceDesc for DiameterGy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiameterGy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.DiameterGy",
	HandlerType: (*DiameterGyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestCreditControl",
			Handler:    _DiameterGy_RequestCreditControl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/gy_interface.proto",
}
