// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: pb/gz_interface.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DiameterGz_StreamCdrLogs_FullMethodName = "/pb.DiameterGz/StreamCdrLogs"
)

// DiameterGzClient is the client API for DiameterGz service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PCEF-Core ➔ OFCS-Collector
// Контракт асинхронных оффлайн-логов Gz: PCEF ➔ OFCS Kafka
type DiameterGzClient interface {
	// Асинхронный слив CDR логов пачками
	StreamCdrLogs(ctx context.Context, in *BulkCdrPack, opts ...grpc.CallOption) (*CdrAck, error)
}

type diameterGzClient struct {
	cc grpc.ClientConnInterface
}

func NewDiameterGzClient(cc grpc.ClientConnInterface) DiameterGzClient {
	return &diameterGzClient{cc}
}

func (c *diameterGzClient) StreamCdrLogs(ctx context.Context, in *BulkCdrPack, opts ...grpc.CallOption) (*CdrAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CdrAck)
	err := c.cc.Invoke(ctx, DiameterGz_StreamCdrLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiameterGzServer is the server API for DiameterGz service.
// All implementations must embed UnimplementedDiameterGzServer
// for forward compatibility.
//
// PCEF-Core ➔ OFCS-Collector
// Контракт асинхронных оффлайн-логов Gz: PCEF ➔ OFCS Kafka
type DiameterGzServer interface {
	// Асинхронный слив CDR логов пачками
	StreamCdrLogs(context.Context, *BulkCdrPack) (*CdrAck, error)
	mustEmbedUnimplementedDiameterGzServer()
}

// UnimplementedDiameterGzServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiameterGzServer struct{}

func (UnimplementedDiameterGzServer) StreamCdrLogs(context.Context, *BulkCdrPack) (*CdrAck, error) {
	return nil, status.Error(codes.Unimplemented, "method StreamCdrLogs not implemented")
}
func (UnimplementedDiameterGzServer) mustEmbedUnimplementedDiameterGzServer() {}
func (UnimplementedDiameterGzServer) testEmbeddedByValue()                    {}

// UnsafeDiameterGzServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiameterGzServer will
// result in compilation errors.
type UnsafeDiameterGzServer interface {
	mustEmbedUnimplementedDiameterGzServer()
}

func RegisterDiameterGzServer(s grpc.ServiceRegistrar, srv DiameterGzServer) {
	// If the following call panics, it indicates UnimplementedDiameterGzServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiameterGz_ServiceDesc, srv)
}

func _DiameterGz_StreamCdrLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkCdrPack)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiameterGzServer).StreamCdrLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiameterGz_StreamCdrLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiameterGzServer).StreamCdrLogs(ctx, req.(*BulkCdrPack))
	}
	return interceptor(ctx, in, info, handler)
}

// DiameterGz_ServiceDesc is the grpc.ServiceDesc for DiameterGz service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiameterGz_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.DiameterGz",
	HandlerType: (*DiameterGzServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StreamCdrLogs",
			Handler:    _DiameterGz_StreamCdrLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/gz_interface.proto",
}
