// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: pb/network_packet.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrafficPipeline_ProcessTrafficStream_FullMethodName = "/pb.TrafficPipeline/ProcessTrafficStream"
)

// TrafficPipelineClient is the client API for TrafficPipeline service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// UE-Emulator ➔ Access-Gateway ➔ PCEF-Core
// Контракт передачи сырого L4-L7 трафика
type TrafficPipelineClient interface {
	// Стриминг сетевых фреймов от Шлюза в PCEF-Core движок
	ProcessTrafficStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RawPacketFrame, EnforcementVerdict], error)
}

type trafficPipelineClient struct {
	cc grpc.ClientConnInterface
}

func NewTrafficPipelineClient(cc grpc.ClientConnInterface) TrafficPipelineClient {
	return &trafficPipelineClient{cc}
}

func (c *trafficPipelineClient) ProcessTrafficStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RawPacketFrame, EnforcementVerdict], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TrafficPipeline_ServiceDesc.Streams[0], TrafficPipeline_ProcessTrafficStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RawPacketFrame, EnforcementVerdict]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrafficPipeline_ProcessTrafficStreamClient = grpc.BidiStreamingClient[RawPacketFrame, EnforcementVerdict]

// TrafficPipelineServer is the server API for TrafficPipeline service.
// All implementations must embed UnimplementedTrafficPipelineServer
// for forward compatibility.
//
// UE-Emulator ➔ Access-Gateway ➔ PCEF-Core
// Контракт передачи сырого L4-L7 трафика
type TrafficPipelineServer interface {
	// Стриминг сетевых фреймов от Шлюза в PCEF-Core движок
	ProcessTrafficStream(grpc.BidiStreamingServer[RawPacketFrame, EnforcementVerdict]) error
	mustEmbedUnimplementedTrafficPipelineServer()
}

// UnimplementedTrafficPipelineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrafficPipelineServer struct{}

func (UnimplementedTrafficPipelineServer) ProcessTrafficStream(grpc.BidiStreamingServer[RawPacketFrame, EnforcementVerdict]) error {
	return status.Error(codes.Unimplemented, "method ProcessTrafficStream not implemented")
}
func (UnimplementedTrafficPipelineServer) mustEmbedUnimplementedTrafficPipelineServer() {}
func (UnimplementedTrafficPipelineServer) testEmbeddedByValue()                         {}

// UnsafeTrafficPipelineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrafficPipelineServer will
// result in compilation errors.
type UnsafeTrafficPipelineServer interface {
	mustEmbedUnimplementedTrafficPipelineServer()
}

func RegisterTrafficPipelineServer(s grpc.ServiceRegistrar, srv TrafficPipelineServer) {
	// If the following call panics, it indicates UnimplementedTrafficPipelineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrafficPipeline_ServiceDesc, srv)
}

func _TrafficPipeline_ProcessTrafficStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TrafficPipelineServer).ProcessTrafficStream(&grpc.GenericServerStream[RawPacketFrame, EnforcementVerdict]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrafficPipeline_ProcessTrafficStreamServer = grpc.BidiStreamingServer[RawPacketFrame, EnforcementVerdict]

// TrafficPipeline_ServiceDesc is the grpc.ServiceDesc for TrafficPipeline service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrafficPipeline_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.TrafficPipeline",
	HandlerType: (*TrafficPipelineServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessTrafficStream",
			Handler:       _TrafficPipeline_ProcessTrafficStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pb/network_packet.proto",
}
