// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pb/network_packet.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RawPacketFrame struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SourceIp         string                 `protobuf:"bytes,1,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`                            // IP-адрес абонента (UE IP)
	DestinationHost  string                 `protobuf:"bytes,2,opt,name=destination_host,json=destinationHost,proto3" json:"destination_host,omitempty"`       // SNI / Host назначения (например, youtube.com)
	PayloadSizeBytes int64                  `protobuf:"varint,3,opt,name=payload_size_bytes,json=payloadSizeBytes,proto3" json:"payload_size_bytes,omitempty"` // Физический размер пакета в байтах
	Timestamp        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RawPacketFrame) Reset() {
	*x = RawPacketFrame{}
	mi := &file_pb_network_packet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawPacketFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawPacketFrame) ProtoMessage() {}

func (x *RawPacketFrame) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_packet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawPacketFrame.ProtoReflect.Descriptor instead.
func (*RawPacketFrame) Descriptor() ([]byte, []int) {
	return file_pb_network_packet_proto_rawDescGZIP(), []int{0}
}

func (x *RawPacketFrame) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *RawPacketFrame) GetDestinationHost() string {
	if x != nil {
		return x.DestinationHost
	}
	return ""
}

func (x *RawPacketFrame) GetPayloadSizeBytes() int64 {
	if x != nil {
		return x.PayloadSizeBytes
	}
	return 0
}

func (x *RawPacketFrame) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type EnforcementVerdict struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SourceIp         string                 `protobuf:"bytes,1,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	Action           string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`                                              // Системный вердикт: "ALLOW", "THROTTLE", "XDP_DROP"
	AllowedBandwidth int64                  `protobuf:"varint,3,opt,name=allowed_bandwidth,json=allowedBandwidth,proto3" json:"allowed_bandwidth,omitempty"` // Скорость в битах/сек, выделенная QoS-шейпером
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EnforcementVerdict) Reset() {
	*x = EnforcementVerdict{}
	mi := &file_pb_network_packet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnforcementVerdict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnforcementVerdict) ProtoMessage() {}

func (x *EnforcementVerdict) ProtoReflect() protoreflect.Message {
	mi := &file_pb_network_packet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnforcementVerdict.ProtoReflect.Descriptor instead.
func (*EnforcementVerdict) Descriptor() ([]byte, []int) {
	return file_pb_network_packet_proto_rawDescGZIP(), []int{1}
}

func (x *EnforcementVerdict) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *EnforcementVerdict) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *EnforcementVerdict) GetAllowedBandwidth() int64 {
	if x != nil {
		return x.AllowedBandwidth
	}
	return 0
}

var File_pb_network_packet_proto protoreflect.FileDescriptor

const file_pb_network_packet_proto_rawDesc = "" +
	"\n" +
	"\x17pb/network_packet.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc0\x01\n" +
	"\x0eRawPacketFrame\x12\x1b\n" +
	"\tsource_ip\x18\x01 \x01(\tR\bsourceIp\x12)\n" +
	"\x10destination_host\x18\x02 \x01(\tR\x0fdestinationHost\x12,\n" +
	"\x12payload_size_bytes\x18\x03 \x01(\x03R\x10payloadSizeBytes\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"v\n" +
	"\x12EnforcementVerdict\x12\x1b\n" +
	"\tsource_ip\x18\x01 \x01(\tR\bsourceIp\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12+\n" +
	"\x11allowed_bandwidth\x18\x03 \x01(\x03R\x10allowedBandwidth2Y\n" +
	"\x0fTrafficPipeline\x12F\n" +
	"\x14ProcessTrafficStream\x12\x12.pb.RawPacketFrame\x1a\x16.pb.EnforcementVerdict(\x010\x01B\x1aZ\x18pcef-shaper-system/pb;pbb\x06proto3"

var (
	file_pb_network_packet_proto_rawDescOnce sync.Once
	file_pb_network_packet_proto_rawDescData []byte
)

func file_pb_network_packet_proto_rawDescGZIP() []byte {
	file_pb_network_packet_proto_rawDescOnce.Do(func() {
		file_pb_network_packet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_network_packet_proto_rawDesc), len(file_pb_network_packet_proto_rawDesc)))
	})
	return file_pb_network_packet_proto_rawDescData
}

var file_pb_network_packet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_network_packet_proto_goTypes = []any{
	(*RawPacketFrame)(nil),        // 0: pb.RawPacketFrame
	(*EnforcementVerdict)(nil),    // 1: pb.EnforcementVerdict
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_pb_network_packet_proto_depIdxs = []int32{
	2, // 0: pb.RawPacketFrame.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: pb.TrafficPipeline.ProcessTrafficStream:input_type -> pb.RawPacketFrame
	1, // 2: pb.TrafficPipeline.ProcessTrafficStream:output_type -> pb.EnforcementVerdict
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_network_packet_proto_init() }
func file_pb_network_packet_proto_init() {
	if File_pb_network_packet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_network_packet_proto_rawDesc), len(file_pb_network_packet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_network_packet_proto_goTypes,
		DependencyIndexes: file_pb_network_packet_proto_depIdxs,
		MessageInfos:      file_pb_network_packet_proto_msgTypes,
	}.Build()
	File_pb_network_packet_proto = out.File
	file_pb_network_packet_proto_goTypes = nil
	file_pb_network_packet_proto_depIdxs = nil
}
