// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: pb/rx_interface.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DiameterRx_SendAAQuery_FullMethodName = "/pb.DiameterRx/SendAAQuery"
)

// DiameterRxClient is the client API for DiameterRx service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AF-Gateway ➔ PCRF-Engine
// Контракт сигнализации Diameter Rx: AF ➔ PCRF
type DiameterRxClient interface {
	// AA-Request / AA-Answer: Запрос на выделение полосы под медиа-поток (IPTV/CDN)
	SendAAQuery(ctx context.Context, in *MediaSessionRequest, opts ...grpc.CallOption) (*MediaSessionResponse, error)
}

type diameterRxClient struct {
	cc grpc.ClientConnInterface
}

func NewDiameterRxClient(cc grpc.ClientConnInterface) DiameterRxClient {
	return &diameterRxClient{cc}
}

func (c *diameterRxClient) SendAAQuery(ctx context.Context, in *MediaSessionRequest, opts ...grpc.CallOption) (*MediaSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MediaSessionResponse)
	err := c.cc.Invoke(ctx, DiameterRx_SendAAQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiameterRxServer is the server API for DiameterRx service.
// All implementations must embed UnimplementedDiameterRxServer
// for forward compatibility.
//
// AF-Gateway ➔ PCRF-Engine
// Контракт сигнализации Diameter Rx: AF ➔ PCRF
type DiameterRxServer interface {
	// AA-Request / AA-Answer: Запрос на выделение полосы под медиа-поток (IPTV/CDN)
	SendAAQuery(context.Context, *MediaSessionRequest) (*MediaSessionResponse, error)
	mustEmbedUnimplementedDiameterRxServer()
}

// UnimplementedDiameterRxServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiameterRxServer struct{}

func (UnimplementedDiameterRxServer) SendAAQuery(context.Context, *MediaSessionRequest) (*MediaSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendAAQuery not implemented")
}
func (UnimplementedDiameterRxServer) mustEmbedUnimplementedDiameterRxServer() {}
func (UnimplementedDiameterRxServer) testEmbeddedByValue()                    {}

// UnsafeDiameterRxServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiameterRxServer will
// result in compilation errors.
type UnsafeDiameterRxServer interface {
	mustEmbedUnimplementedDiameterRxServer()
}

func RegisterDiameterRxServer(s grpc.ServiceRegistrar, srv DiameterRxServer) {
	// If the following call panics, it indicates UnimplementedDiameterRxServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiameterRx_ServiceDesc, srv)
}

func _DiameterRx_SendAAQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MediaSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiameterRxServer).SendAAQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiameterRx_SendAAQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiameterRxServer).SendAAQuery(ctx, req.(*MediaSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiameterRx_ServiceDesc is the grpc.ServiceDesc for DiameterRx service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiameterRx_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.DiameterRx",
	HandlerType: (*DiameterRxServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendAAQuery",
			Handler:    _DiameterRx_SendAAQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/rx_interface.proto",
}
