// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: pb/subscriber_profile.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SubscriptionRepository_FetchProfile_FullMethodName = "/pb.SubscriptionRepository/FetchProfile"
)

// SubscriptionRepositoryClient is the client API for SubscriptionRepository service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PCRF-Engine ➔ SPR-Storage
// Контракт базы данных SPR: PCRF ➔ SPR
type SubscriptionRepositoryClient interface {
	// Извлечение b2b-паспорта контракта из ScyllaDB
	FetchProfile(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*SubscriberProfileResponse, error)
}

type subscriptionRepositoryClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscriptionRepositoryClient(cc grpc.ClientConnInterface) SubscriptionRepositoryClient {
	return &subscriptionRepositoryClient{cc}
}

func (c *subscriptionRepositoryClient) FetchProfile(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*SubscriberProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriberProfileResponse)
	err := c.cc.Invoke(ctx, SubscriptionRepository_FetchProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubscriptionRepositoryServer is the server API for SubscriptionRepository service.
// All implementations must embed UnimplementedSubscriptionRepositoryServer
// for forward compatibility.
//
// PCRF-Engine ➔ SPR-Storage
// Контракт базы данных SPR: PCRF ➔ SPR
type SubscriptionRepositoryServer interface {
	// Извлечение b2b-паспорта контракта из ScyllaDB
	FetchProfile(context.Context, *ProfileRequest) (*SubscriberProfileResponse, error)
	mustEmbedUnimplementedSubscriptionRepositoryServer()
}

// UnimplementedSubscriptionRepositoryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubscriptionRepositoryServer struct{}

func (UnimplementedSubscriptionRepositoryServer) FetchProfile(context.Context, *ProfileRequest) (*SubscriberProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchProfile not implemented")
}
func (UnimplementedSubscriptionRepositoryServer) mustEmbedUnimplementedSubscriptionRepositoryServer() {
}
func (UnimplementedSubscriptionRepositoryServer) testEmbeddedByValue() {}

// UnsafeSubscriptionRepositoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubscriptionRepositoryServer will
// result in compilation errors.
type UnsafeSubscriptionRepositoryServer interface {
	mustEmbedUnimplementedSubscriptionRepositoryServer()
}

func RegisterSubscriptionRepositoryServer(s grpc.ServiceRegistrar, srv SubscriptionRepositoryServer) {
	// If the following call panics, it indicates UnimplementedSubscriptionRepositoryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SubscriptionRepository_ServiceDesc, srv)
}

func _SubscriptionRepository_FetchProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionRepositoryServer).FetchProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionRepository_FetchProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionRepositoryServer).FetchProfile(ctx, req.(*ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SubscriptionRepository_ServiceDesc is the grpc.ServiceDesc for SubscriptionRepository service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubscriptionRepository_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SubscriptionRepository",
	HandlerType: (*SubscriptionRepositoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchProfile",
			Handler:    _SubscriptionRepository_FetchProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/subscriber_profile.proto",
}
